### ISSUE TITLE
Jumping repeatedly allows reaching arbitrary velocity

### ISSUE THREAD

**Issue by empiricist** [thecodewarrior/Hooked#1]
I found this strange bug when playing around with the dev build.  
Steps to replicate:
- Install Hook-Mod (you do not need to have a hook equipped though).
- Press the space bar as fast as possible (in survival, so you won't start flying instead).  This can take a few tries, but you can give yourself a jump boost effect to make getting started easier.  
- Reach escape velocity.

This also seems to affect velocity in different directions, but it is easiest to demonstrate for going up.   I suspect it is caused by [this](https://github.com/thecodewarrior/Hook-Mod/blob/815763b75f8be24ee37e20a3448218b83e6c22ca/src/main/java/com/thecodewarrior/hooks/proxy/ClientProxy.java#L76-L84) section, as it only seems to happen when pull is toggled on or the player is crouching.

**Comment by thecodewarrior** [comment]
Closed as the relevant code no longer exists.
